options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chanwoo-academy', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chanwoo-academy']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'chanwoo-academy'
      - '--image=gcr.io/$PROJECT_ID/chanwoo-academy'
      - '--region=asia-northeast3'
      - '--allow-unauthenticated'
    entrypoint: 'gcloud'

images:
  - 'gcr.io/$PROJECT_ID/chanwoo-academy'
